

; This is an automatically generated library file. Do not edit this file manually.
; This file contains enrivonment variables for the VM architecture. 

.archlib

    ; Architecture details

    %= ADDRESS_SIZE 8
    %= INSTRUCTION_SIZE 1
    %= INTERRUPT_CODE_SIZE 1
    %= ERROR_CODE_SIZE 4

    ; Built-in error codes

    %= UNEXPECTED_EOF_ERROR_CODE -2
    %= GENERIC_ERROR_CODE -1
    %= NO_ERROR_CODE 0
    %= EOF_ERROR_CODE 1

    ; Interrupt codes

    %= PRINT1_INTR 0
    %= PRINT2_INTR 1
    %= PRINT4_INTR 2
    %= PRINT8_INTR 3
    %= PRINT_BYTES_INTR 4
    %= PRINT_CHAR_INTR 5
    %= PRINT_STRING_INTR 6
    %= PRINT_STATIC_BYTES_INTR 7
    %= PRINT_STATIC_STRING_INTR 8
    %= READ_BYTES_INTR 9
    %= READ_ALL_INTR 10

    